### PR TITLE
Extend "list" output to include size, format with columns

### PR DESCRIPTION
**Pull request by camh-**
Extend the `list` command to also output the size of the image as stored in the
registry. Format the output into columns and with a header to present a little
nicer.

This uses a new `GetManifest` method so we can calculate the size.

### CODE REVIEW

**Review by juliaogris — APPROVED** [review]
That is soo neat! Really quickly becoming pretty comprehensive.
I guess now it's only auth that's a bit of a mystery.
How are you using this? Just with your personal docker registry?

I like the package names

Well done, this really panning out just like you wanted. very cool (and obvious)

💚

**Comment by juliaogris** [comment]
And then I was like: Am I going insane? I'm sure you hadn't renamed all these packages last time...
You snuck in a refactor PR without me knowing. I'm stunned.
I can't believe you went with my suggestions. I think that has never happened in my career, that anybody just went with my suggestions.

**Comment by juliaogris** [comment]
This tool is starting to get really cool.
i think it is starting to get deserving of a PR, maybe even CI ;)

**Comment by camh-** [comment]
> I guess now it's only auth that's a bit of a mystery.

I started thinking about this. It is a shame that the `grpc.Options` argument is completely unusable. It is an interface with private methods only so it is completely unusable.

I expect I'll add a constructor for `httprule.Client` that can take options. Whether I add a specific auth option or just a `WithHeader` option, I'm not sure but It will be usable to set the auth token in the `Authorization` header. I have a need for auth now as I want to list the contents of our AWS registry for work. So I should have that soon.

**Comment by camh-** [comment]
> How are you using this? Just with your personal docker registry?

Yeah. I have a couple of images there since I had to build my own unifi image (needed to fix a bug), and I pushed a few extra images just for testing. I do intend to test with AWS ECR but I need to add auth for that.

**Pull request merged**
